### ISSUE TITLE
User cannot specify different path to data base file

### ISSUE THREAD

**Issue by sergey-koryshev** [sergey-koryshev/Idler#14]
User cannot specify different path to data base file

Error:
```log
09/02/2022 17:16:58 [Information] (3) Checking if Data Base exists: "C:\ShiftDB.mdb"
09/02/2022 17:16:58 [Error] (1) System.TypeInitializationException: The type initializer for 'Idler.Helpers.DB.DataBaseConnection' threw an exception. ---> System.Data.OleDb.OleDbException: Not a valid file name.
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at Idler.Helpers.DB.DataBaseConnection..cctor() in D:\a\Idler\Idler\src\Idler\Helpers\DB\DataBaseConnection.cs:line 51
   --- End of inner exception stack trace ---
   at Idler.Helpers.DB.DataBaseConnection.GetRowCollectionAsync(String query, List`1 parameters)
   at Idler.Shift.<>c__DisplayClass29_0.<<RefreshAsync>b__0>d.MoveNext() in D:\a\Idler\Idler\src\Idler\Shift.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Idler.Shift.<RefreshAsync>d__29.MoveNext() in D:\a\Idler\Idler\src\Idler\Shift.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Idler.MainWindow.<InitializeCurrentShift>d__21.MoveNext() in D:\a\Idler\Idler\src\Idler\MainWindow.xaml.cs:line 109
```

**Comment by sergey-koryshev** [comment]
It's probably due to quotes in the path

**Comment by sergey-koryshev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User cannot specify different path to data base file](https://trello.com/c/tWfShVfU/12-user-cannot-specify-different-path-to-data-base-file)
